# Generated by Django 3.2 on 2021-04-11 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=120)),
                ('courseNumber', models.CharField(max_length=8)),
                ('sectionNumber', models.CharField(max_length=4)),
                ('Course_Description', models.TextField(max_length=500)),
                ('meetingDay', models.CharField(max_length=4)),
                ('meetingTime', models.CharField(max_length=5)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
