# Generated by Django 3.2 on 2021-04-12 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Enrolled_Classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled_class',
            name='Course_Description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='enrolled_class',
            name='meetingDay',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='enrolled_class',
            name='meetingTime',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='enrolled_class',
            name='professor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
