# Generated by Django 3.2 on 2021-04-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enrolled_Classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_day',
            name='meetingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting_day',
            name='meetingTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
