# Generated by Django 3.2 on 2021-04-26 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Enrolled_Classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingDate', models.DateField(blank=True, null=True)),
                ('meetingString', models.CharField(blank=True, max_length=14, null=True)),
                ('meetingTime', models.TimeField(blank=True, null=True)),
                ('randomString', models.CharField(max_length=11)),
                ('absent', models.ManyToManyField(blank=True, related_name='absent', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='Enrolled_Classes.enrolled_class')),
                ('late', models.ManyToManyField(blank=True, related_name='late', to=settings.AUTH_USER_MODEL)),
                ('not_applicable', models.ManyToManyField(blank=True, related_name='not_applicable', to=settings.AUTH_USER_MODEL)),
                ('present', models.ManyToManyField(blank=True, related_name='present', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
