name: Upload to server

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run update
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd /home/github/blackboard_companion; ./update.sh
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY}}